from enum import Enum


class UserRole(str, Enum):
    ADMIN = "ADMIN"
    TEAM_LEAD = "TEAM_LEAD"
    TEAM_MEMBER = "TEAM_MEMBER"


class ExecutionStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    IN_PROGRESS = "IN_PROGRESS"
    BLOCKED = "BLOCKED"
    PASSED = "PASSED"
    FAILED = "FAILED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    TEST_AGENT_SUPPORT = "TEST_AGENT_SUPPORT"
    SDK_SUPPORT_MISSING = "SDK_SUPPORT_MISSING"
    TEST_STEPS_MISSING = "TEST_STEPS_MISSING"


class AutoAssignStrategy(str, Enum):
    ROUND_ROBIN = "ROUND_ROBIN"
    EQUAL_DISTRIBUTION = "EQUAL_DISTRIBUTION"
    TECHNOLOGY_BASED = "TECHNOLOGY_BASED"
    PRIORITY_BASED = "PRIORITY_BASED"


class ActivityAction(str, Enum):
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    ASSIGN = "ASSIGN"
    REASSIGN = "REASSIGN"
    STATUS_CHANGE = "STATUS_CHANGE"
    IMPORT = "IMPORT"
    EXPORT = "EXPORT"
    JIRA_CREATE = "JIRA_CREATE"
    LOGIN = "LOGIN"
